---
- name: Check if dropbox is installed
  command: dpkg-query -W dropbox
  register: my_package_check_deb
  failed_when: my_package_check_deb.rc > 1
  changed_when: my_package_check_deb.rc == 1

- name: Download dropbox
  get_url:
    url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
    dest: /tmp/
  when: my_package_check_deb.rc == 1

- name: Install dropbox
  apt: deb="/tmp/dropbox_2020.03.04_amd64.deb"
  become: yes
  when: my_package_check_deb.rc == 1

- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - rake
    - git
    - zsh
    - vim
    - ranger
    - emacs
    - x11-xkb-utils
    - node-gyp
    - python3-gpg
    - npm
    - nodejs
    - libffi-dev
    - libreadline-dev
    - libsqlite3-dev
    - exfat-fuse
    - exfat-utils
    - tmux
    - htop
    - snap
    - latte-dock
    - qt5-style-kvantum
    - qt5-style-kvantum-themes
    - korganizer
    - appmenu-gtk2-module
    - appmenu-gtk3-module
    - kdepim
    - kubectl
    - cmake
    - gnome-tweak-tool
    - gnome-calendar
    - steam
    - openssh-server
    - build-essential
    - zlib1g-dev
    - libffi-dev
    - libssl-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - liblzma-dev

- name: Install rbenv
  shell: brew install rbenv

- name: Install python packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - python3-pip
    - python3-virtualenv
    - virtualenvwrapper

- name: Install python modules
  pip:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: Install apps
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - fonts-firacode
    - thunderbird

- name: Install snap apps in classic mode
  snap:
    name: "{{ item }}"
    classic: yes
  become: yes
  with_items:
    - ubuntu-make
    - pycharm-professional
    - rubymine

- name: Install snap apps in standard mode
  snap:
    name: "{{ item }}"
    classic: no
  become: yes
  with_items:
    - rocketchat-desktop
    - discord
    - doctl

- name: Grant doctl permissions
  shell: snap connect doctl:kube-config
  become: yes

- name: Set caps as esc
  shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
